apiVersion: v1
kind: Service
metadata:
  name: mars-rover-svc
  labels:
    name: mars-rover-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
    nodePort: 30000
  selector:
    name: mars-rover-svc
