---
apiVersion: v1
kind: Service
metadata:
  name: mars-rover-test
  labels:
    name: mars-rover-test
  namespace: mars-rover-test-ns
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30005
  selector:
    name: mars-rover-test