---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mars-rover-1
  namespace: mars-rover-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mars-rover
      version: 0.2.0
  template:
    metadata:
      labels:
        name: mars-rover
        version: 0.2.0
    spec:
      containers:
      - name: mars-rover-con
        image: XXX
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
          limits:
            cpu: 300m
            memory: 1000Mi
        env:
        - name: SESSION_REDIS
          value: "true"
        ports:
        - containerPort: 5000
