name: Test CI-CD GKE workflow

on:
  push:
    branches:
    - test

# Environment variables available to all jobs and steps in this workflow
env:
  GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
  GCLOUD_EMAIL: ${{ secrets.GCLOUD_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GCLOUD_ZONE: europe-west1-b
  GCLOUD_CLUSTER: mars-rover-test
  IMAGE: mars-rover-test-image

jobs:
  build-tests:
    name: build-tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
        
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GCLOUD_EMAIL }}
        service_account_key: ${{ secrets.GCLOUD_KEY }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker
      
    # Build the Docker image
    - name: Build
      run: |        
        docker build -t gcr.io/"$GCLOUD_PROJECT"/"$IMAGE":"$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" https://github.com/NandosJake/MarsRover.git#test

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |
        docker push gcr.io/$GCLOUD_PROJECT/$IMAGE:$GITHUB_SHA
        
    # Set up kustomize
    - name: Set up Kustomize
      run: |
        curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |
        gcloud container clusters get-credentials $GCLOUD_CLUSTER --zone $GCLOUD_ZONE --project $GCLOUD_PROJECT
        ./kustomize edit set image gcr.io/$GCLOUD_PROJECT/$IMAGE:${GITHUB_SHA}
        kubectl apply -f mars-rover-test-ns.yaml
        kubectl apply -f mars-rover-test-svc.yaml
        kubectl apply -f mars-rover-test-dep.yaml
        kubectl get services -o wide
