name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
    - uses: actions/checkout@v1
      
    - name: Build the docker image 
      run: docker build . --file Dockerfile --tag eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}
      
    - name: Authenticate into Google Cloud Platform
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      
    - name: Configure Docker to use Google Cloud Platform
      uses: actions/gcloud/cli@master
      with:
        args: "auth configure-docker --quiet"
      
    - name: Push image to Google Cloud Container Registry
      uses: actions/gcloud/cli@master
      with:
        entrypoint: sh
        args: -c "docker push eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}"
    
    - name: Login to Docker hub 
      run: docker login --username "nandosjakeh" --password "Slamwtbeirir95"
      
    - name: push the Docker image
      run: docker push nandosjakeh/marsrover
